### PR TITLE
Set `allow-discrete` (if supported) for observed properties only

### LINKED ISSUE #105: transition-behavior is now applied to all elements... is it safe?
https://github.com/LeaVerou/style-observer/commit/aa0435c844319af66f6ac4cbface6907b6c59ad2 introduced a change that resulted in `transition-behavior: allow-discrete !important` being applied to all elements within the document root rather than just the observed elements as before. 

As a result, we started experiencing tab crashes in Chrome 130 - 132 on Windows. The issue appears when the `transition-behavior` property is applied to an element with `position: absolute`, which is later updated with properties like `top` and `left`.

While this is likely to be a browser bug, as the crash doesn't occur in newer Chrome versions, I'm wondering: is it actually a good idea for style-observer to apply `transition-behavior` indiscriminately to all elements in the document? If a stylesheet includes a rule with `transition: all 1s`, wouldn't adding `transition-behavior: allow-discrete` affect its behavior? For example, previously setting `display: none` would immediately hide the element, but with `allow-discrete`, wouldn't that change to being delayed?

### PR DESCRIPTION
**Pull request by DmitrySharabin**
Revert changes in aa0435c844319af66f6ac4cbface6907b6c59ad2. Fixes #105

### CODE REVIEW

File: src/element-style-observer.js [hunk 1]
```diff
@@ -234,10 +223,19 @@ export default class ElementStyleObserver {
 
 		properties = [...new Set(properties)]; // Dedupe
 
-		// Only add properties not already present and not excluded
+		let supportsAllowDiscrete = CSS.supports("transition-behavior", "allow-discrete");
```
Comment (LeaVerou) [inline src/element-style-observer.js:226]: This is not going to change. Just set it as a `const` on the outside. I would also suggest setting it to `" allow-discrete"` if true and `''` if false, then you can just append it when you need it instead of having to use a conditional.

Comment (DmitrySharabin) [reply src/element-style-observer.js]: Makes sense. Fixed!

File: src/element-style-observer.js [hunk 2]
```diff
@@ -234,10 +223,12 @@ export default class ElementStyleObserver {
 
 		properties = [...new Set(properties)]; // Dedupe
 
-		// Only add properties not already present and not excluded
+		const allowDiscrete = CSS.supports("transition-behavior", "allow-discrete") ? " allow-discrete" : "";
```
Comment (LeaVerou) [inline src/element-style-observer.js:226]: I meant you can set it **outside the class**. This is not going to change the entire time the page is loaded (it could only change if the browser is updated!)

**Review by LeaVerou — APPROVED** [review]
See comment, LGTM otherwise!

File: src/element-style-observer.js (hunk 2 above)
Comment (DmitrySharabin) [reply src/element-style-observer.js]: Fixed!
